### ISSUE TITLE
Flow as an email approval editor OOTB

### ISSUE THREAD

**Issue by tillo13** [manywho/service-email#13]
Teemu Hyle
Has anyone been able to create Flow that send an email with approve/reject links (or something similar)?
Or any idea how to do it? 
Something *without* SF or other external systems. I know there is a demo that use SF service for that.
I tried to create something with inputs like described here (https://developers-old.manywho.com/display/MA/Sending+inputs+to+a+Flow), but it looks that inputs can only be sent when initializing a new Flow, and not when joining like from link from an email... Or is it possible send new inputs when joining back to Flow?

people interested
@chubbyjesus,  @Teemu Hyle, @jonjomckay 

edited, cleaning description

**Comment by josecollazzi** [comment]
@jonjomckay could you please review?

**Comment by jonjomckay** [comment]
@josecollazzi this will probably work better like how it's implemented in the Salesforce service - the links are built from the outcomes to the next map elements, as that way you can just progress the flow with all the same authentication context and state, etc.

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review the changes?

**Comment by josecollazzi** [comment]
@jonjomckay could you please take a look again to the changes after the review?
?

**Comment by jonjomckay** [comment]
@josecollazzi LGTM

**Comment by josecollazzi** [comment]
Thanks @jonjomckay,  great code review :sake:

**Comment by josecollazzi** [comment]
@tillo13 

Brief description of this feature:

The message action "Send Email with Decision Request" is executed by the flow, then this action read the outcomes from the message action itself and add each one as a choice, when the person who receives the email click in the link then the outcome is chosen and the flow continues in that direction, the Recipient output of the message action it will be populated with the email of the person who clicked first.
