### ISSUE TITLE
Update simple-java-mail dependency

### ISSUE THREAD

**Issue by jonjomckay** [manywho/service-email#2]
The library we're using to send the emails (`simple-java-mail`) changed its package name and we're a few versions out of date, so we should update the dependency version to:

```xml
<dependency>
    <groupId>org.simplejavamail</groupId>
    <artifactId>simple-java-mail</artifactId>
    <version>{latest.version}</version>
</dependency>
```

**Comment by jonjomckay** [comment]
@josecollazzi could you review please?

**Comment by josecollazzi** [comment]
@jonjomckay  LGTM 🚶
