### ISSUE TITLE
A list from the Contact Type has no binding to choose

### ISSUE THREAD

**Issue by DAtkinson64** [manywho/service-email#7]
It seems there is no Contact Type binding that links to a List or Object created from the Contact Type?  Here are my steps:

1.  I created a list from Contact Type from ManyWho Email Service.
2.  I created an Object from Contact Type from ManyWho Email Service.
3.  I need to populate the List with email addresses. 
4.  If I try to load to the To Contact Object, there is nothing to choose in the "where will data be sourced from". (see attached)
5.  If I try to load to the To -Requestor List, there is nothing to choose in the "where will data be sourced from".

I don't  see any other way to populate the list in order to send a non-simple email to a list of recipients.  

Deborah Atkinson
![no binding contact type](https://user-images.githubusercontent.com/22374118/30487226-b10614d8-99e7-11e7-8e6e-1ca930d27a08.png)

GearsCRM

**Comment by ghost** [comment]
@DAtkinson64 You can try this steps:
(this question is more about tooling that email service)

1) [Create a list of contacts](https://s3.amazonaws.com/files-manywho-com/0e82cff4-503a-4628-9075-176219f1a17d/create%20a%20list%20of%20contacts.png)

2) [Import the list of contacts in your flow](https://s3.amazonaws.com/files-manywho-com/0e82cff4-503a-4628-9075-176219f1a17d/create%20a%20list%20of%20contacts2.png)

3) use that list for send email
