### ISSUE TITLE
User's Box OR S3 should be usable for email's attachments

### ISSUE THREAD

**Issue by aryakumargeorge** [manywho/service-email#9]
The service currently requires the flow user to upload file(s) provided by service's S3 to be able to attach them to email.
Flow users should be able to attach file(s) from their own Box or S3 - identifying this via service's configuration parameters.

**Comment by josecollazzi** [comment]
@aryakumargeorge  I have created a new branch for you and make your pull request.
You can close now https://github.com/manywho/service-email/pull/8

**Comment by josecollazzi** [comment]
The code have been reviewed
